- name: databricks-import-directory
  uses: microsoft/databricks-import-notebook@v1.0.0
  with:
    # Databricks host
    databricks-host: 'https://adb-1434202335462086.6.azuredatabricks.net/'
    # Databricks token
    databricks-token: 'dapi96345018d5882439f88069c7db05c84d-3'
    # LOCAL_NOTEBOOKS_PATH
    local-path: './notebook'
    # REMOTE_NOTEBOOK_PATH
    remote-path: './shared/notebooks'
