name: Notebook Deployment - Databricks
on:
  workflow_call:
    inputs:
      databricks_code_path:
        description: Workspace/Shared/notebooks
        type: string
        required: true
      
      service_code_file:
        description: notebook/testing_ci_notebooks2.py
        type: string
        required: true
    
  secrets:
    DATABRICKS_HOST_URL:
      description:   'https://adb-1434202335462086.6.azuredatabricks.net/'
      required: true
    DATABRICKS_TOKEN:
      description: 'dapi96345018d5882439f88069c7db05c84d-3'
      required: true

jobs:
  push_to_db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3.3.0
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        run: |
            pip install databricks-cli 
            cat > ~/.databrickscfg << EOF 
            [DEFAULT] 
            host = ${{ secrets.DATABRICKS_HOST_URL }} 
            token = ${{ secrets.DATABRICKS_TOKEN }} 
            jobs-api-version = 2.1 
            EOF 
    
      - name: Deploy code to databricks workspace
        run: |
            databricks workspace import ${{ inputs.service_code_file }} ${{ inputs.databricks_code_path }} --language python --overwrite
